#file name: ex> application-dev.yml

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: [ db-url ]
    username: [ db-username ]
    password: [ db-password ]

  flyway:
    #    enabled: true
    enabled: false
    baseline-on-migrate: true
    url: [ db-url ]
    user: [ db-username ]
    password: [ db-password ]

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: [ file-path ]

  mail:
    host: smtp.gmail.com
    port: 587
    username: [ mail@example.com ]
    password: [ mail-password ]
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql: trace

app:
  url: http://localhost:8081