spring:
  application:
    name: sb-board

  profiles:
    group:
      dev: dev
      test: test
      prod: prod

  jpa:
    hibernate:
      ddl-auto: none # db migrate ?
      #      ddl-auto: validate # default
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8

  session:
    store-type: jdbc
    timeout: 600
    jdbc:
      initialize-schema: never

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  main:
    allow-bean-definition-overriding: true

  messages:
    always-use-message-format: false
    basename: messages
    cache-duration: -1
    encoding: UTF-8
    fallback-to-system-locale: true

  data:
    web:
      pageable:
        #        one-indexed-parameters: true
        default-page-size: 10

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG